package SitaApi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-08T11:13:57.860+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "SitaApi", 
                  wsdlLocation = "http://localhost:15012/SitaApi.asmx?WSDL",
                  targetNamespace = "http://cims.nl/") 
public class SitaApi extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cims.nl/", "SitaApi");
    public final static QName SitaApiSoap12 = new QName("http://cims.nl/", "SitaApiSoap12");
    public final static QName SitaApiSoap = new QName("http://cims.nl/", "SitaApiSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:15012/SitaApi.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SitaApi.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:15012/SitaApi.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public SitaApi(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SitaApi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SitaApi() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SitaApi(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SitaApi(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SitaApi(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SitaApiSoap
     */
    @WebEndpoint(name = "SitaApiSoap12")
    public SitaApiSoap getSitaApiSoap12() {
        return super.getPort(SitaApiSoap12, SitaApiSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SitaApiSoap
     */
    @WebEndpoint(name = "SitaApiSoap12")
    public SitaApiSoap getSitaApiSoap12(WebServiceFeature... features) {
        return super.getPort(SitaApiSoap12, SitaApiSoap.class, features);
    }


    /**
     *
     * @return
     *     returns SitaApiSoap
     */
    @WebEndpoint(name = "SitaApiSoap")
    public SitaApiSoap getSitaApiSoap() {
        return super.getPort(SitaApiSoap, SitaApiSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SitaApiSoap
     */
    @WebEndpoint(name = "SitaApiSoap")
    public SitaApiSoap getSitaApiSoap(WebServiceFeature... features) {
        return super.getPort(SitaApiSoap, SitaApiSoap.class, features);
    }

}
