
package SitaApi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-30T11:31:57.967+02:00
 * Generated source version: 3.1.5
 * 
 */
public final class SitaApiSoap_SitaApiSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://cims.nl/", "SitaApi");

    private SitaApiSoap_SitaApiSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SitaApi.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SitaApi ss = new SitaApi(wsdlURL, SERVICE_NAME);
        SitaApiSoap port = ss.getSitaApiSoap();  
        
        {
        System.out.println("Invoking getMediaOfIncidentF...");
        java.lang.String _getMediaOfIncidentF_token = "";
        int _getMediaOfIncidentF_incident = 0;
        java.lang.String _getMediaOfIncidentF_filter = "";
        int _getMediaOfIncidentF_start = 0;
        int _getMediaOfIncidentF_limit = 0;
        ArrayOfMedia _getMediaOfIncidentF__return = port.getMediaOfIncidentF(_getMediaOfIncidentF_token, _getMediaOfIncidentF_incident, _getMediaOfIncidentF_filter, _getMediaOfIncidentF_start, _getMediaOfIncidentF_limit);
        System.out.println("getMediaOfIncidentF.result=" + _getMediaOfIncidentF__return);


        }
        {
        System.out.println("Invoking addToxication...");
        java.lang.String _addToxication_token = "";
        java.lang.String _addToxication_name = "";
        java.lang.String _addToxication_description = "";
        java.lang.String _addToxication_chemicalCompound = "";
        int _addToxication_dangerLevel = 0;
        double _addToxication_volatility = 0.0;
        boolean _addToxication__return = port.addToxication(_addToxication_token, _addToxication_name, _addToxication_description, _addToxication_chemicalCompound, _addToxication_dangerLevel, _addToxication_volatility);
        System.out.println("addToxication.result=" + _addToxication__return);


        }
        {
        System.out.println("Invoking getMedia...");
        java.lang.String _getMedia_token = "";
        int _getMedia_start = 0;
        int _getMedia_limit = 0;
        ArrayOfMedia _getMedia__return = port.getMedia(_getMedia_token, _getMedia_start, _getMedia_limit);
        System.out.println("getMedia.result=" + _getMedia__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_username = "";
        java.lang.String _login_password = "";
        java.lang.String _login__return = port.login(_login_username, _login_password);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking getMediaOfIncident...");
        java.lang.String _getMediaOfIncident_token = "";
        int _getMediaOfIncident_incident = 0;
        int _getMediaOfIncident_start = 0;
        int _getMediaOfIncident_limit = 0;
        ArrayOfMedia _getMediaOfIncident__return = port.getMediaOfIncident(_getMediaOfIncident_token, _getMediaOfIncident_incident, _getMediaOfIncident_start, _getMediaOfIncident_limit);
        System.out.println("getMediaOfIncident.result=" + _getMediaOfIncident__return);


        }
        {
        System.out.println("Invoking sendMessageWithMedia...");
        java.lang.String _sendMessageWithMedia_token = "";
        int _sendMessageWithMedia_team = 0;
        java.lang.String _sendMessageWithMedia_message = "";
        int _sendMessageWithMedia_mediaId = 0;
        boolean _sendMessageWithMedia__return = port.sendMessageWithMedia(_sendMessageWithMedia_token, _sendMessageWithMedia_team, _sendMessageWithMedia_message, _sendMessageWithMedia_mediaId);
        System.out.println("sendMessageWithMedia.result=" + _sendMessageWithMedia__return);


        }
        {
        System.out.println("Invoking logout...");
        boolean _logout__return = port.logout();
        System.out.println("logout.result=" + _logout__return);


        }
        {
        System.out.println("Invoking getToxications...");
        java.lang.String _getToxications_token = "";
        ArrayOfToxication _getToxications__return = port.getToxications(_getToxications_token);
        System.out.println("getToxications.result=" + _getToxications__return);


        }
        {
        System.out.println("Invoking getMediaF...");
        java.lang.String _getMediaF_token = "";
        java.lang.String _getMediaF_filter = "";
        int _getMediaF_start = 0;
        int _getMediaF_limit = 0;
        ArrayOfMedia _getMediaF__return = port.getMediaF(_getMediaF_token, _getMediaF_filter, _getMediaF_start, _getMediaF_limit);
        System.out.println("getMediaF.result=" + _getMediaF__return);


        }
        {
        System.out.println("Invoking sendMessage...");
        java.lang.String _sendMessage_token = "";
        int _sendMessage_team = 0;
        java.lang.String _sendMessage_message = "";
        boolean _sendMessage__return = port.sendMessage(_sendMessage_token, _sendMessage_team, _sendMessage_message);
        System.out.println("sendMessage.result=" + _sendMessage__return);


        }
        {
        System.out.println("Invoking editIncident...");
        java.lang.String _editIncident_token = "";
        int _editIncident_id = 0;
        java.lang.String _editIncident_name = "";
        java.lang.String _editIncident_description = "";
        java.lang.String _editIncident_chemicalCompound = "";
        int _editIncident_dangerLevel = 0;
        double _editIncident_volatility = 0.0;
        boolean _editIncident__return = port.editIncident(_editIncident_token, _editIncident_id, _editIncident_name, _editIncident_description, _editIncident_chemicalCompound, _editIncident_dangerLevel, _editIncident_volatility);
        System.out.println("editIncident.result=" + _editIncident__return);


        }
        {
        System.out.println("Invoking getIncidents...");
        java.lang.String _getIncidents_token = "";
        int _getIncidents_start = 0;
        int _getIncidents_limit = 0;
        ArrayOfIncident _getIncidents__return = port.getIncidents(_getIncidents_token, _getIncidents_start, _getIncidents_limit);
        System.out.println("getIncidents.result=" + _getIncidents__return);


        }

        System.exit(0);
    }

}
